databases:
- cluster_name: web-scheduler-prod
  engine: MYSQL
  name: web-scheduler-prod
  production: true
  version: "8"
- cluster_name: web-scheduler-redis
  engine: REDIS
  name: web-scheduler-redis
  production: true
  version: "6"
domains:
- domain: scheduler.nullreference.io
  type: PRIMARY
name: web-scheduler
region: nyc
services:
 - name: web-scheduler-server
   envs:
      - key: ASPNETCORE_ENVIRONMENT
        scope: RUN_AND_BUILD_TIME
        value: Production
      - key: Kestrel__Endpoints__Http__Url
        scope: RUN_TIME
        value: http://*:80
      - key: Storage__Invariant
        scope: RUN_AND_BUILD_TIME
        value: MySql.Data.MySqlClient
      - key: Storage__ConnectionString
        scope: RUN_TIME
        value: Server=${web-scheduler-prod.HOSTNAME};Port=${web-scheduler-prod.PORT};Database=orleans;UserId=${web-scheduler-prod.USERNAME};Password=${web-scheduler-prod.PASSWORD};SslMode=Required;
   health_check:
     http_path: /status/self
     port: 80
   http_port: 8080
   image:
     registry_type: DOCR
     repository: web-scheduler-server
     tag: 0.1.4
   instance_count: 3
   instance_size_slug: professional-xs
   internal_ports:
   - 11111
   - 30000
   - 80
   routes:
     - path: /OrleansDashboard
 - name: web-scheduler-api
   envs:
   - key: Redis__ConnectionString
     scope: RUN_TIME
     value: ${web-scheduler-redis.HOSTNAME}:${web-scheduler-redis.PORT},user=${web-scheduler-redis.USERNAME},password=${web-scheduler-redis.PASSWORD},Ssl=true
   - key: Kestrel__Endpoints__Http__Url
     scope: RUN_TIME
     value: http://*:80
   - key: ForwardedHeaders__AllowedHosts
     scope: RUN_TIME
     value: ${APP_DOMAIN}
   - key: ASPNETCORE_ENVIRONMENT
     scope: RUN_AND_BUILD_TIME
     value: Production
   - key: Storage__Invariant
     scope: RUN_AND_BUILD_TIME
     value: MySql.Data.MySqlClient
   - key: Storage__ConnectionString
     scope: RUN_TIME
     value: Server=${web-scheduler-prod.HOSTNAME};Port=${web-scheduler-prod.PORT};Database=orleans;UserId=${web-scheduler-prod.USERNAME};Password=${web-scheduler-prod.PASSWORD};SslMode=Required;
   http_port: 80
   image:
     registry_type: DOCR
     repository: web-scheduler-api
     tag: 0.1.1
   instance_count: 2
   instance_size_slug: professional-xs
   routes:
     - path: /api
   health_check:
     http_path: /status
     port: 80
static_sites:
- environment_slug: html
  github:
    branch: release
    deploy_on_push: true
    repo: web-scheduler/web-scheduler-frontend
  name: web-scheduler-frontend
  routes:
  - path: /
